# Generated by Django 3.2 on 2022-12-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
